# Generated by Django 4.2.16 on 2024-09-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('cream', 'Cream'), ('other', 'Other')], default='other', max_length=20)),
                ('age_in_months', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
