# Generated by Django 4.2.16 on 2024-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittymart', '0002_kitten_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='breed',
            field=models.CharField(choices=[('persian', 'Persian'), ('maine_coon', 'Maine Coon'), ('siamese', 'Siamese'), ('bengal', 'Bengal'), ('sphynx', 'Sphynx'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
